# Generated by Django 4.2.11 on 2024-05-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="token",
        ),
    ]
