# Generated by Django 4.2.11 on 2024-05-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="isConfigured",
            field=models.BooleanField(default=False),
        ),
    ]
