# Generated by Django 4.2.11 on 2024-05-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_isconfigured"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="isConfigured",
            new_name="is_configured",
        ),
    ]
