# Generated by Django 4.2.11 on 2024-06-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("demande", "0003_alter_demande_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEtudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demande.demande",
                    ),
                ),
            ],
        ),
    ]
