# Generated by Django 4.2.11 on 2024-03-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etudiant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etudiant",
            old_name="confirmation",
            new_name="confirm",
        ),
        migrations.RenameField(
            model_name="etudiant",
            old_name="mot_de_passe",
            new_name="password",
        ),
    ]
