# Generated by Django 4.2.11 on 2024-04-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etudiant", "0002_rename_confirmation_etudiant_confirm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etudiant",
            name="confirm",
        ),
    ]
