# Generated by Django 4.2.11 on 2024-05-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiant", "0004_alter_etudiant_options_alter_etudiant_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="date_naissance",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="education",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="fb_lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="git_lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="in_lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="lettre_motivation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="link_lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="sexe",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="telephone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="twit_lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="yout_lien",
            field=models.URLField(blank=True, null=True),
        ),
    ]
