# Generated by Django 4.2.11 on 2024-05-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("etudiant", "0005_etudiant_bio_etudiant_date_naissance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile_photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                (
                    "etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_photo",
                        to="etudiant.etudiant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cv_upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cv", models.FileField(blank=True, null=True, upload_to="cv_upload/")),
                (
                    "etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_upload",
                        to="etudiant.etudiant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.FileField(blank=True, null=True, upload_to="certificats/"),
                ),
                (
                    "etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificats",
                        to="etudiant.etudiant",
                    ),
                ),
            ],
        ),
    ]
