# Generated by Django 4.2.11 on 2024-05-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etudiant", "0006_profile_photo_cv_upload_certificats"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificats",
            old_name="cv",
            new_name="certificats",
        ),
    ]
