# Generated by Django 4.2.11 on 2024-05-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiant", "0009_etudiant_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cv_upload",
            name="etudiant",
        ),
        migrations.RemoveField(
            model_name="profile_photo",
            name="etudiant",
        ),
        migrations.AddField(
            model_name="etudiant",
            name="certificats",
            field=models.FileField(blank=True, null=True, upload_to="certificats/"),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cv_upload/"),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="profile_cover",
            field=models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.DeleteModel(
            name="Certificats",
        ),
        migrations.DeleteModel(
            name="Cv_upload",
        ),
        migrations.DeleteModel(
            name="Profile_photo",
        ),
    ]
