# Generated by Django 4.2.11 on 2024-05-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiant", "0010_remove_cv_upload_etudiant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="domain",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
