# Generated by Django 4.2.11 on 2024-05-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etudiant", "0011_alter_etudiant_domain_alter_etudiant_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etudiant",
            name="twit_lien",
        ),
        migrations.RemoveField(
            model_name="etudiant",
            name="yout_lien",
        ),
    ]
