# Generated by Django 4.2.11 on 2024-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiant", "0012_remove_etudiant_twit_lien_remove_etudiant_yout_lien"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
