# Generated by Django 4.2.11 on 2024-05-03 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "entreprise",
            "0002_alter_entreprise_options_alter_entreprise_managers_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "minimal_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "maximal_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("number_of_interns", models.IntegerField()),
                ("skills", models.TextField()),
                ("binome", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("offer_type", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entreprise.entreprise",
                    ),
                ),
            ],
        ),
    ]
