# Generated by Django 4.2.11 on 2024-05-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0003_offer_workspace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="workspace",
        ),
    ]
