# Generated by Django 4.2.11 on 2024-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0004_remove_offer_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="offer",
            name="skills",
        ),
        migrations.AddField(
            model_name="offer",
            name="skills",
            field=models.ManyToManyField(to="offer.skill"),
        ),
    ]
