# Generated by Django 4.2.11 on 2024-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0006_remove_offer_skills_delete_skill_offer_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="skills",
            field=models.CharField(max_length=255),
        ),
    ]
