# Generated by Django 4.2.11 on 2024-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0009_skill_remove_offer_skills_offer_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="skills",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="offer",
            name="skills",
            field=models.JSONField(default=list),
        ),
    ]
