# Generated by Django 4.2.11 on 2024-05-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0010_remove_offer_skills_delete_skill_offer_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="binome",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="offer",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="domain",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="offer",
            name="duration",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="offer",
            name="education",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="offer",
            name="expirationDate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="offer",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="offer",
            name="maximal_payment",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="offer",
            name="minimal_payment",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="offer",
            name="number_of_interns",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="offer",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="offer",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
