# Generated by Django 4.2.11 on 2024-05-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etudiant", "0013_etudiant_blocked"),
        ("entreprise", "0016_entreprise_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavorisEntreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entreprise.entreprise",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etudiant.etudiant",
                    ),
                ),
            ],
        ),
    ]
