# Generated by Django 4.2.11 on 2024-05-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entreprise", "0016_entreprise_verified"),
        ("offer", "0012_alter_offer_maximal_payment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="books/")),
                ("text", models.TextField()),
                ("titre", models.CharField(max_length=255)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="entreprise.entreprise",
                    ),
                ),
                (
                    "offers",
                    models.ManyToManyField(related_name="books", to="offer.offer"),
                ),
            ],
        ),
    ]
