# Generated by Django 4.2.11 on 2024-06-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_file_alter_book_text_alter_book_titre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="template",
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
