# Generated by Django 4.2.11 on 2024-05-05 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "entreprise",
            "0002_alter_entreprise_options_alter_entreprise_managers_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Pfebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="pfe_books")),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entreprise.entreprise",
                    ),
                ),
            ],
        ),
    ]
