# Generated by Django 4.2.11 on 2024-05-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0015_alter_entreprise_profile_cover_and_more"),
        ("pfebook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pfebook",
            name="entreprise",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pfe_book",
                to="entreprise.entreprise",
            ),
        ),
    ]
