# Generated by Django 4.2.11 on 2024-05-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pfebook", "0002_alter_pfebook_entreprise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pfebook",
            name="title",
        ),
    ]
