# Generated by Django 4.2.11 on 2024-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfebook", "0003_remove_pfebook_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="pfebook",
            name="titre",
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
