# Generated by Django 4.2.11 on 2024-03-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("secteur", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("confirm", models.CharField(max_length=100)),
            ],
        ),
    ]
