# Generated by Django 4.2.11 on 2024-04-20 10:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entreprise", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entreprise",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="entreprise",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="entreprise",
            name="confirm",
        ),
        migrations.RemoveField(
            model_name="entreprise",
            name="email",
        ),
        migrations.RemoveField(
            model_name="entreprise",
            name="id",
        ),
        migrations.RemoveField(
            model_name="entreprise",
            name="nom",
        ),
        migrations.RemoveField(
            model_name="entreprise",
            name="password",
        ),
        migrations.AddField(
            model_name="entreprise",
            name="customuser_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
