# Generated by Django 4.2.11 on 2024-05-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "entreprise",
            "0002_alter_entreprise_options_alter_entreprise_managers_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile_logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_logos/"
                    ),
                ),
                (
                    "entreprise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_logo",
                        to="entreprise.entreprise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile_cover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.FileField(blank=True, null=True, upload_to="cover_photos/"),
                ),
                (
                    "entreprise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_photos",
                        to="entreprise.entreprise",
                    ),
                ),
            ],
        ),
    ]
