# Generated by Django 4.2.11 on 2024-05-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0003_profile_logo_profile_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entreprise",
            name="numero",
        ),
        migrations.AddField(
            model_name="entreprise",
            name="date_etablissement",
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entreprise",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="email_rh",
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="fb_lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="in_lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="link_lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="nom_rh",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="nombre_equipe",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="prenom_rh",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="site_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="telephone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="telephone_rh",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="twit_lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="type_industrie",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="type_organisation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="vision",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="yout_lien",
            field=models.URLField(blank=True, null=True),
        ),
    ]
