# Generated by Django 4.2.11 on 2024-05-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0004_remove_entreprise_numero_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entreprise",
            name="secteur",
        ),
    ]
