# Generated by Django 4.2.11 on 2024-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0005_remove_entreprise_secteur"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="nom",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
