# Generated by Django 4.2.11 on 2024-05-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0006_entreprise_nom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile_cover",
            old_name="cv",
            new_name="image",
        ),
    ]
