# Generated by Django 4.2.11 on 2024-05-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0007_rename_cv_profile_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_cover",
            name="entreprise",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profil_cover",
                to="entreprise.entreprise",
            ),
        ),
    ]
