# Generated by Django 4.2.11 on 2024-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0008_alter_profile_cover_entreprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="date_etablissement",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
