# Generated by Django 4.2.11 on 2024-05-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0010_alter_profile_cover_entreprise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile_logo",
            name="entreprise",
        ),
        migrations.AddField(
            model_name="entreprise",
            name="cover_photo",
            field=models.ImageField(
                default="default/téléchargé.jpeg", upload_to="cover_photos/"
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="profile_photo",
            field=models.ImageField(
                default="default/Default-pfp.jpg", upload_to="profile_photos/"
            ),
        ),
        migrations.DeleteModel(
            name="Profile_cover",
        ),
        migrations.DeleteModel(
            name="Profile_logo",
        ),
    ]
