# Generated by Django 4.2.11 on 2024-05-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0011_remove_profile_logo_entreprise_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entreprise",
            old_name="cover_photo",
            new_name="profile_cover",
        ),
        migrations.RenameField(
            model_name="entreprise",
            old_name="profile_photo",
            new_name="profile_logo",
        ),
    ]
