# Generated by Django 4.2.11 on 2024-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0013_alter_entreprise_profile_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="profile_cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="localhost:8080cover_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="profile_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="localhost:8080/profile_photos/"
            ),
        ),
    ]
