# Generated by Django 4.2.11 on 2024-05-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0014_alter_entreprise_profile_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="profile_cover",
            field=models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="profile_logo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
