# Generated by Django 4.2.11 on 2024-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0015_alter_entreprise_profile_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
