# Generated by Django 4.2.11 on 2024-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boitemessagerie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagerie",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="messages/files/"),
        ),
        migrations.AlterField(
            model_name="messagerie",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
