# Generated by Django 4.2.11 on 2024-06-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etudiant", "0013_etudiant_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomtemplate", models.CharField(max_length=255)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etudiant.etudiant",
                    ),
                ),
            ],
        ),
    ]
