# Generated by Django 4.2.11 on 2024-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demande",
            name="status",
            field=models.CharField(blank=True, default="en attente", max_length=100),
        ),
    ]
