# Generated by Django 4.2.11 on 2024-05-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etudiant", "0013_etudiant_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApparitionProfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("nombre_apparitions", models.IntegerField(default=0)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etudiant.etudiant",
                    ),
                ),
            ],
            options={
                "unique_together": {("etudiant", "date")},
            },
        ),
    ]
